# Exposes ports to host.
version: '2.1'

services:
  tcpserver:
    build:
        context: .
        dockerfile: ./docker/chat-server/Dockerfile
    command: ["/usr/local/bin/chat-server", "-server-addr", "0.0.0.0:4000", "-server-mode", "tcp"]
    volumes:
      - ./contrib/message-schema.json:/tmp/message-schema.json
    ports:
      - 4000:4000
    expose:
      - 4000
    links:
      - redis

  websocketserver:
    build:
        context: .
        dockerfile: ./docker/chat-server/Dockerfile
    command: ["/usr/local/bin/chat-server", "-server-addr", "0.0.0.0:4001", "-server-mode", "ws"]
    volumes:
      - ./contrib/message-schema.json:/tmp/message-schema.json
    ports:
      - 4001:4001
    expose:
      - 4001
    links:
      - redis

  redis:
    image: redis:3.2-alpine
    ports:
        - 6379:6379
    stop_signal: SIGKILL
    healthcheck:
      # redis-cli likes to return exit code 0, so check stdout instead
      test: redis-cli -h redis ping | grep PONG
      interval: 1s
      retries: 5
      timeout: 500ms
